# Generated by Django 3.0.5 on 2020-12-01 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Company')),
                ('field', models.CharField(max_length=100, verbose_name='Field of Internship')),
                ('stipend', models.FloatField(verbose_name='Stipend')),
                ('duration', models.CharField(max_length=50, verbose_name='Duration')),
                ('location', models.CharField(max_length=100, verbose_name='Location')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Name')),
                ('password', models.CharField(max_length=20, verbose_name='Password')),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collegename', models.CharField(max_length=100, verbose_name='College Name')),
                ('gpa', models.CharField(max_length=10, verbose_name='GPA')),
                ('internship1', models.CharField(blank=True, max_length=100, null=True, verbose_name='Internship 1')),
                ('internship2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Internship 2')),
                ('internship3', models.CharField(blank=True, max_length=100, null=True, verbose_name='Internship 3')),
                ('project1', models.CharField(blank=True, max_length=100, null=True, verbose_name='Project 1')),
                ('project2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Project 2')),
                ('project3', models.CharField(blank=True, max_length=100, null=True, verbose_name='Project 3')),
                ('skill1', models.CharField(blank=True, max_length=100, null=True, verbose_name='Skill 1')),
                ('skill2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Skill 2')),
                ('skill3', models.CharField(blank=True, max_length=100, null=True, verbose_name='Skill 3')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.CustomUser', verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1', models.TextField(verbose_name='Question 1')),
                ('q2', models.TextField(verbose_name='Question 2')),
                ('q3', models.TextField(verbose_name='Question 3')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Company', verbose_name='Company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.CustomUser', verbose_name='User')),
            ],
        ),
    ]
